'use client';

import Navbar from '@/components/Navbar';
import { Providers } from './providers';
import { Rubik } from 'next/font/google';
import { Box } from '@chakra-ui/react';

const rubik = Rubik({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Providers>
          <Navbar />
          {children}
        </Providers>
      </body>
    </html>
  );
}
